apiVersion: apps/v1
kind: Deployment
metadata: 
  name: spring-deployment
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata: 
      labels:
        app: spring
    spec:
      containers:
       - name: spring
         image: yasantha1995/misynergy:latest
         ports:
           - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring
  ports:
   - protocol: TCP
     port: 30000
     targetPort: 8080   